- name: Install Aptitude
  sudo: yes
  apt:
    name: aptitude
    state: latest

- name: APT Get + Upgrade
  sudo: yes
  apt:
    update-cache: yes
    upgrade: full

- name: Add VirtualBox APT Key
  sudo: yes
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc 
    state: present
    id: 98AB5139

- name: Add Dropbox APT Key
  sudo: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Add Additional APT Repostories
  sudo: yes
  apt_repository: "repo='{{ item }}' state=present"
  with_items: apt_repos

- name: Install APT Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: apt_packages

- name: Install PIP Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items: pip_packages

- name: Create Dev Directory
  file: path={{ ansible_env.HOME}}/Development
        state=directory

- name: Download Zprezto Git Repo
  git:
    repo: git@github.com:MichaelAquilina/prezto.git
    dest: '{{ ansible_env.HOME }}/.zprezto'

- name: Download Dev Git Repos
  git:
    repo: '{{ item.repo }}'
    dest: '{{ ansible_env.HOME }}/Development/{{ item.folder }}'
  with_items:
    - { repo: 'git@github.com:MichaelAquilina/todolist.git', folder: todolist }
    - { repo: 'git@github.com:MichaelAquilina/whatismyip.git', folder: whatismyip }

