- name: Install Aptitude
  sudo: yes
  apt:
    name: aptitude
    state: latest

- name: Add VirtualBox APT Key
  sudo: yes
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc 
    state: present
    id: 98AB5139

- name: Add Additional APT Keys
  sudo: yes
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }}
  with_items: apt_keys

- name: Add Additional APT Repostories
  sudo: yes
  apt_repository: "repo='{{ item }}' state=present"
  with_items: apt_repos

- name: APT Update + Upgrade
  sudo: yes
  apt:
    update-cache: yes
    upgrade: full

- name: Install APT Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: apt_packages

- name: Install PIP Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items: pip_packages

- name: Add known_hosts github.com key
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Setup Conifguration Files
  command: creates={{ item.dest }} ln -s {{ ansible_env.PWD }}/roles/ubuntu-mike/files/{{ item.filename }} {{ item.dest }}
  with_items:
    - {filename: tigrc, dest: ~/.tigrc }
    - {filename: nanorc, dest: ~/.nanorc }
    - {filename: gitconfig, dest: ~/.gitconfig }
    - {filename: vimrc, dest: ~/.vimrc }

- name: Setup terminator dir
  file: path=~/.config/terminator state=directory

- name: Setup terminator
  command: ln -s {{ ansible_env.PWD }}/roles/ubuntu-mike/files/terminator_config ~/.config/terminator/config
  args:
     creates: ~/.config/terminator/config

- name: Setup Synapse dir
  file: path=~/.config/synapse state=directory

- name: Setup Synapse
  command: ln -s {{ ansible_env.PWD }}/roles/ubuntu-mike/files/synapse_config.json ~/.config/synapse/config.json
  args:
     creates: ~/.config/synapse/config.json

- name: Install Vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: no

- name: mkidr vim
  file: path=~/.vim/colors state=directory

- name: Install Vim Molokai Theme
  get_url:
    url: https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
    dest: ~/.vim/colors/molokai.vim

- name: Change Default Shell to Zsh
  sudo: yes
  user:
    name: '{{ ansible_env.USER }}'
    shell: /bin/zsh

- name: Download Zprezto Git Repo
  git:
    repo: git@github.com:MichaelAquilina/prezto.git
    dest: '{{ ansible_env.HOME }}/.zprezto'
    recursive: yes
    update: no

- name: Setup Zprezto
  command: creates={{ ansible_env.HOME }}/.zshrc roles/ubuntu-mike/files/zprezto_setup.sh 

- name: Setup dircolors
  command: creates={{ ansible_env.HOME }}/.dircolors ln -s ~/.zprezto/dircolors.molokai ~/.dircolors

- name: Create Dev Directory
  file: path={{ ansible_env.HOME}}/Development
        state=directory

- name: Download Dev Git Repos
  git:
    repo: '{{ item.repo }}'
    dest: '{{ ansible_env.HOME }}/Development/{{ item.folder }}'
    update: no
  with_items:
    - { repo: 'git@github.com:MichaelAquilina/todolist.git', folder: todolist }
    - { repo: 'git@github.com:MichaelAquilina/whatismyip.git', folder: whatismyip }


- name: Setup Launch Items
  gsetting:
    user: '{{ ansible_env.USER }}'
    path: com.canonical.Unity.Launcher
    key: favorites
    value: >
          ['application://org.gnome.Nautilus.desktop',
           'application://terminator.desktop',
           'application://firefox.desktop',
           'unity://running-apps', 'unity://devices']

- name: Setup Indicator Multiload
  gsetting: user=None path={{ item.path }} key={{ item.key }} value={{ item.value }}
  with_items:
    - {path: de.mh21.indicator-multiload.general, key: color-scheme, value: traditional}
    - {path: de.mh21.indicator-multiload.graphs.mem, key: enabled, value: 'true'}
    - {path: de.mh21.indicator-multiload.graphs.net, key: enabled, value: 'true'}
    - {path: de.mh21.indicator-multiload.graphs.load, key: enabled, value: 'false'}
    - {path: de.mh21.indicator-multiload.graphs.disk, key: enabled, value: 'true'}
    - {path: de.mh21.indicator-multiload.graphs.swap, key: enabled, value: 'false'}

- name: Setup Compiz
  gsetting:
    user: None
    path: org.compiz.place:/org/compiz/profiles/unity/plugins/place/
    key: mode
    value: "1"

- name: Notify Completion
  debug:
    msg: "Setup complete. Don't forget to install Steam and sign in to Dropbox!"

