- name: Install Aptitude
  sudo: yes
  apt:
    name: aptitude
    state: latest

- name: Add VirtualBox APT Key
  sudo: yes
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc 
    state: present
    id: 98AB5139

- name: Add Additional APT Keys
  sudo: yes
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }}
  with_items: apt_keys

- name: Add Additional APT Repostories
  sudo: yes
  apt_repository: "repo='{{ item }}' state=present"
  with_items: apt_repos

- name: APT Update + Upgrade
  sudo: yes
  apt:
    update-cache: yes
    upgrade: full

- name: Install APT Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: apt_packages

- name: Install PIP Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items: pip_packages

- name: Check Dropbox Status
  command: dropbox running
  register: dropbox_state
  changed_when: False

- name: Dropbox Status
  debug: "msg={{ dropbox_state.stdout }}"

- name: Download Dropbox Daemon
  shell: "yes | DISPLAY='' dropbox start -i"
  when: dropbox_state.stdout == ''

- name: Change Default Shell to Zsh
  sudo: yes
  user:
    name: '{{ ansible_env.USER }}'
    shell: /bin/zsh

- name: Download Zprezto Git Repo
  git:
    repo: git@github.com:MichaelAquilina/prezto.git
    dest: '{{ ansible_env.HOME }}/.zprezto'
    recursive: yes

- name: Create Dev Directory
  file: path={{ ansible_env.HOME}}/Development
        state=directory

- name: Download Dev Git Repos
  git:
    repo: '{{ item.repo }}'
    dest: '{{ ansible_env.HOME }}/Development/{{ item.folder }}'
  with_items:
    - { repo: 'git@github.com:MichaelAquilina/todolist.git', folder: todolist }
    - { repo: 'git@github.com:MichaelAquilina/whatismyip.git', folder: whatismyip }

- name: Notify Completion
  debug:
    msg: "Setup complete. Don't forget to install Steam and sign in to Dropbox!"

