- name: Show date
  gsettings:
    schema: org.gnome.desktop.interface
    key: clock-show-date
    value: "true"

- name: Never Auto-run with Removable Media
  gsettings:
    schema: org.gnome.desktop.media-handling
    key: autorun-never
    value: "true"

- name: Set Close Window Shortcuts
  gsettings:
    schema: org.gnome.desktop.wm.keybindings
    key: close
    value: "['<Alt>q', '<Alt>F4']"

- name: Sort Directories First
  gsettings:
    schema: org.gnome.nautilus.preferences
    key: sort-directories-first
    value: "true"

- name: List Folder View
  gsettings:
    schema: org.gnome.nautilus.preferences
    key: default-folder-viewer
    value: "list-view"

- name: Install OpenVPN gnome
  sudo: yes
  apt:
    pkg: network-manager-openvpn-gnome
    state: latest

- name: Only Display Windows from current Workspace in switchers
  gsettings:
    schema: "{{ item }}"
    key: current-workspace-only
    value: 'true'
  with_items:
    - org.gnome.shell.app-switcher
    - org.gnome.shell.window-switcher

# Not installed automatically
- name: System Monitor Dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
    - gir1.2-gtop-2.0
    - gir1.2-networkmanager-1.0

- name: Install Github Gnome Shell Extensions
  shell_extension:
    uri: "https://github.com/MichaelAquilina/{{ item.uri }}.git"
    name: "{{ item.name }}"
    state: enabled
    subfolder: "{{ item.subfolder }}"
  with_items:
    - {uri: "gse-refresh-wifi", name: "refresh-wifi@kgshank.net", subfolder: "refresh-wifi@kgshank.net"}
    - {uri: "gnome-shell-system-monitor-applet", name: "system-monitor@paradoxxx.zero.gmail.com", subfolder: "system-monitor@paradoxxx.zero.gmail.com"}
    - {uri: "pixel-saver", name: "pixel-saver@deadalnix.me", subfolder: "pixel-saver@deadalnix.me"}
    - {uri: "gnome-shell-extension-stealmyfocus", name: "steal-my-focus@kagesenshi.org", subfolder: ""}
    - {uri: "topicons", name: "topIcons@kevinboxhoorn.yahoo.com", subfolder: ""}
    - {uri: "nohotcorner", name: "nohotcorner@azuri.free.fr", subfolder: ""}
    - {uri: "status-title-bar", name: "StatusTitleBar@devpower.org", subfolder: "src"}

- name: Enable inbuilt Gnome Shell extensions
  shell_extension:
    name: "{{ item }}"
    state: enabled
  with_items:
    - drive-menu@gnome-shell-extensions.gcampax.github.com

# TODO: Restart gnome shell on change with `gnome-shell --replace`

- name: Gtk3 Settings
  file:
    src: "{{ ansible_env.PWD }}/roles/gnomeshell/files/gtk3_settings.ini"
    dest: ~/.config/gtk-3.0/settings.ini
    force: yes
    state: link

- name: Gtk3 Custom CSS Theming
  file:
    src: "{{ ansible_env.PWD }}/roles/gnomeshell/files/gtk.css"
    dest: ~/.config/gtk-3.0/gtk.css
    force: yes
    state: link

- name: Spotify autoscaling script
  sudo: yes
  file:
    src: "{{ ansible_env.PWD }}/roles/gnomeshell/files/spotify-autoscale"
    dest: /usr/bin/spotify-autoscale
    state: link

- name: Update Spotify Desktop File to use AutoScale
  sudo: yes
  lineinfile:
    dest: "{{ item }}"
    regexp: "^Exec="
    state: present
    line: "Exec=spotify-autoscale"
  with_items:
    - /usr/share/spotify/spotify.desktop
    - /usr/share/applications/spotify.desktop

- name: Update Google Chrome Desktop file to use GPU workaround
  sudo: yes
  ini_file:
    dest: /usr/share/applications/google-chrome.desktop
    section: "Desktop Entry"
    option: "Exec"
    value: "/usr/bin/google-chrome-stable --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers %U"

- name: Update Google Chrome Desktop file New Window to use GPU workaround
  sudo: yes
  ini_file:
    dest: /usr/share/applications/google-chrome.desktop
    section: "NewWindow Shortcut Group"
    option: "Exec"
    value: "/usr/bin/google-chrome-stable --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers"

- name: Update Google Chrome Desktop file Icongnito to use GPU workaround
  sudo: yes
  ini_file:
    dest: /usr/share/applications/google-chrome.desktop
    section: "NewIncognito Shortcut Group"
    option: "Exec"
    value: "/usr/bin/google-chrome-stable --incognito --disable-gpu-driver-bug-workarounds --enable-native-gpu-memory-buffers"

- name: Disable Natural Scrolling on Touchpad
  gsettings:
    schema: org.gnome.desktop.peripherals.touchpad
    key: natural-scroll
    value: "false"

- name: Automatically clean Temp/Trash files
  gsettings:
    schema: org.gnome.desktop.privacy
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - {key: remove-old-temp-files, value: "false"}  # Do not enable - Interferes with gpgagent
    - {key: remove-old-trash-files, value: "true"}
    - {key: old-files-age, value: "uint32 1"}

- name: Focus windows on creation
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: focus-new-windows
    value: "strict"

- name: Center Windows
  gsettings:
    schema: org.gnome.mutter
    key: center-new-windows
    value: "true"

- name: Set Icon and Theme
  gsettings:
    schema: org.gnome.desktop.interface
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - {key: gtk-theme, value: "Numix"}
    - {key: icon-theme, value: "gnome"}

- name: Resize with right button
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: resize-with-right-button
    value: "true"

- name: Move Windows with Alt Key
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: mouse-button-modifier
    value: "<Alt>"

- name: Switch Windows with Alt+Tab
  gsettings:
    schema: org.gnome.desktop.wm.keybindings
    key: switch-windows
    value: "['<Alt>Tab']"

- name: Set Media Control Key Shortcuts
  gsettings:
    schema: org.gnome.settings-daemon.plugins.media-keys
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - {key: next, value: "<Primary>KP_Right"}
    - {key: previous, value: "<Primary>KP_Left"}
    - {key: play, value: "<Primary>KP_5"}

- name: Set Gnomeshell favourites
  gsettings:
    schema: org.gnome.shell
    key: favorite-apps
    value: "['google-chrome.desktop', 'terminator.desktop', 'org.gnome.Polari.desktop', 'org.gnome.Nautilus.desktop', 'wireshark.desktop']"

- name: Display Reminders in Notification Area Only
  gsettings:
    schema: org.gnome.evolution.calendar
    key: notify-with-tray
    value: "true"

- name: Remove NoDisplay from Gnome Shortucts
  sudo: yes
  ini_file:
    dest: "{{ item }}"
    option: NoDisplay
    value: "false"
    section: "Desktop Entry"
  with_items:
    - "/usr/share/applications/gnome-background-panel.desktop"
    - "/usr/share/applications/gnome-bluetooth-panel.desktop"
    - "/usr/share/applications/gnome-datetime-panel.desktop"
    - "/usr/share/applications/gnome-display-panel.desktop"
    - "/usr/share/applications/gnome-keyboard-panel.desktop"
    - "/usr/share/applications/gnome-mouse-panel.desktop"
    - "/usr/share/applications/gnome-network-panel.desktop"
    - "/usr/share/applications/gnome-power-panel.desktop"
    - "/usr/share/applications/gnome-printers-panel.desktop"
    - "/usr/share/applications/gnome-privacy-panel.desktop"
    - "/usr/share/applications/gnome-sound-panel.desktop"
    - "/usr/share/applications/gnome-user-accounts-panel.desktop"

- name: Create autostart directory
  file:
    path: ~/.config/autostart
    state: directory

- name: Set Startup applications
  file:
    state: link
    force: yes
    src: "{{ ansible_env.PWD }}/roles/gnomeshell/files/autostart/{{ item }}"
    dest: ~/.config/autostart/{{ item }}
  with_items:
    - caffeine.desktop
    - redshift-gtk.desktop
    - gnome-keyring-ssh.desktop  # Actually disables SSH in gnome-keyring

- name: Setup Gnome Bookmarks
  template:
    src: bookmarks.j2
    dest: ~/.config/gtk-3.0/bookmarks
    force: yes

- name: Set Wallpaper
  gsettings:
    schema: org.gnome.desktop.background
    key: picture-uri
    value: "{{ ansible_env.PWD }}/roles/gnomeshell/files/wallpaper.jpeg"

- name: Set Screensaver Wallpaper
  gsettings:
    schema: org.gnome.desktop.screensaver
    key: picture-uri
    value: "file:///usr/share/backgrounds/Greenish_by_EstebanMitnick.jpg"
