- name: Show date
  gsettings:
    schema: org.gnome.desktop.interface
    key: clock-show-date
    value: "true"

- name: Always open windows in the center
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: focus-new-windows
    value:  "'center'"

- name: Set theme
  gsettings:
    schema: org.gnome.desktop.interface
    key: gtk-theme
    value: "'Numix'"

- name: Resize with right button
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: resize-with-right-button
    value: "true"
