- name: Show date
  gsettings:
    schema: org.gnome.desktop.interface
    key: clock-show-date
    value: "true"

- name: System Monitor Dependencies
  sudo: yes
  apt: name={{ item }}
  with_items:
    - gir1.2-gtop-2.0
    - gir1.2-networkmanager-1.0

- name: Install Gnome Shell Extensions
  shell_extension: "uri=git@github.com:{{ item.uri }}.git name={{ item.name }} state=enabled subfolder={{ item.subfolder }}"
  with_items:
    - {uri: "kgshank/gse-refresh-wifi", name: "refresh-wifi@kgshank.net", subfolder: "refresh-wifi@kgshank.net"}
    - {uri: "paradoxxxzero/gnome-shell-system-monitor-applet", name: "system-monitor@paradoxxx.zero.gmail.com", subfolder: "system-monitor@paradoxxx.zero.gmail.com"}
    - {uri: "deadalnix/pixel-saver", name: "pixel-saver@deadalnix.me", subfolder: "pixel-saver@deadalnix.me"}
    - {uri: "MichaelAquilina/gnome-shell-extension-stealmyfocus", name: "steal-my-focus@kagesenshi.org", subfolder: ""}
    - {uri: "MichaelAquilina/gnome-shell-extension-appindicator", name: "appindicatorsupport@rgcjonas.gmail.com", subfolder: ""}
    - {uri: "HROMANO/nohotcorner", name: "nohotcorner@azuri.free.fr", subfolder: ""}

# TODO: Restart gnome shell on change with `gnome-shell --replace`

- name: Gtk3 Settings
  file:
    src: "{{ ansible_env.PWD }}/roles/gnomeshell/files/gtk3_settings.ini"
    dest: ~/.config/gtk-3.0/settings.ini
    force: yes
    state: link

- name: Spotify autoscaling script
  sudo: yes
  file:
    src: "{{ ansible_env.PWD }}/roles/gnomeshell/files/spotify-autoscale"
    dest: /usr/bin/spotify-autoscale
    state: link

- name: Update Spotify Desktop File to use AutoScale
  sudo: yes
  lineinfile:
    dest: "{{ item }}"
    regexp: "^Exec="
    state: present
    line: "Exec=spotify-autoscale"
  with_items:
    - /usr/share/spotify/spotify.desktop
    - /usr/local/share/applications/spotify.desktop

- name: Focus windows on creation
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: focus-new-windows
    value: "'strict'"

- name: Center Windows
  gsettings:
    schema: org.gnome.mutter
    key: center-new-windows
    value: "true"

- name: Set Icon and Theme
  gsettings: schema=org.gnome.desktop.interface key={{ item.key }} value={{ item.value }}
  with_items:
    - {key: gtk-theme, value: "\\'Numix\\'"}
    - {key: icon-theme, value: "\\'gnome\\'"}

- name: Resize with right button
  gsettings:
    schema: org.gnome.desktop.wm.preferences
    key: resize-with-right-button
    value: "true"

- name: Remove NoDisplay from Gnome Shortucts
  sudo: yes
  ini_file: "dest={{ item }} option=NoDisplay value=false section='Desktop Entry'"
  with_items:
    - "/usr/share/applications/gnome-background-panel.desktop"
    - "/usr/share/applications/gnome-bluetooth-panel.desktop"
    - "/usr/share/applications/gnome-datetime-panel.desktop"
    - "/usr/share/applications/gnome-display-panel.desktop"
    - "/usr/share/applications/gnome-keyboard-panel.desktop"
    - "/usr/share/applications/gnome-mouse-panel.desktop"
    - "/usr/share/applications/gnome-network-panel.desktop"
    - "/usr/share/applications/gnome-power-panel.desktop"
    - "/usr/share/applications/gnome-printers-panel.desktop"
    - "/usr/share/applications/gnome-sound-panel.desktop"

- name: Set Wallpaper
  gsettings:
    schema: org.gnome.desktop.background
    key: picture-uri
    value: "'{{ ansible_env.PWD }}/roles/gnomeshell/files/wallpaper.jpeg'"

- name: Set Screensaver Wallpaper
  gsettings:
    schema: org.gnome.desktop.screensaver
    key: picture-uri
    value: "'file:///usr/share/backgrounds/Greenish_by_EstebanMitnick.jpg'"
