apt_repos:
  - 'deb http://ppa.launchpad.net/mercurial-ppa/releases/ubuntu trusty main'
  - 'ppa:fkrull/deadsnakes'

apt_keys:
  - {keyserver: keyserver.ubuntu.com, id: 323293EE}  # Mercurial

apt_packages:
  - vim
  - at
  - curl
  - cmatrix
  - most
  - zsh
  - htop
  - pandoc
  - python-setuptools
  - jq
  - lame
  - tig
  - tree
  - cowsay
  - xsel
  - whois
  - cabal-debian
  - cabal-install
  # Development
  - python-dev
  - python2.6
  - python3-dev
  - python2.6-dev
  - python3.2
  - python3.2-dev
  - python3.3
  - python3.3-dev
  - git
  - mercurial
  - g++
  - gfortran
  - liblapack3
  - libblas3
  - golang
  - golang-go.tools
  - gocode
  - shellcheck
  - coffeescript

pip_packages:
  - distribute  # Force upgrade
  - pip  # Force upgrade
  - ipython
  - virtualenvwrapper
  - numpy
  - pandas
  - tox
  - cookiecutter
