- name: Setup Atom Packages
  apm: name={{ item }}
  with_items:
    - atom-beautify
    - atom-dark-fusion-syntax
    - atom-jinja2
    - atom-material-syntax
    - autocomplete-python
    - file-icons
    - highlight-selected
    - hyperclick
    - keybinding-cheatsheet
    - language-r
    - linter
    - linter-flake8
    - linter-shellcheck
    - nucleus-dark-ui
    - python-isort
    - rulerz
    - sort-lines
    - vim-mode

- name: Setup linking to Atom config.cson
  file:
    dest: ~/.atom/config.cson
    force: yes
    state: link
    src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_config.cson"

- name: Setup linking to Atom keymap file
  file:
    dest: ~/.atom/keymap.cson
    force: yes
    state: link
    src: "{{ ansible_env.PWD }}/roles/gnome/files/atom_keymap.cson"
