- name: Add Docker GPG Key
  become: yes
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Add Docker Repoistory
  become: yes
  apt_repository:
     repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"

- name: Install Docker
  become: yes
  apt:
    name: docker-engine

- name: Create Docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add Current User to Docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started
