- name: Install Aptitude
  sudo: yes
  apt:
    name: aptitude
    state: latest

- name: Add Apt Keys
  sudo: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
  with_items: apt_keys

- name: Add Apt Repos
  sudo: yes
  apt_repository: "state=present repo='{{ item }}'"
  with_items: apt_repos

- name: Install APT Packages
  sudo: yes
  apt: pkg={{ item }} state=present update_cache=yes
  with_items: apt_packages

- name: Setup node symbolic link
  sudo: yes
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link

- name: Create htop config folder
  file:
    state: directory
    mode: 0700
    path: ~/.config/htop

- name: Setup Configuration Files
  file: dest={{ item.dest }} force=yes state=link src={{ ansible_env.PWD }}/roles/ubuntu/files/{{ item.filename }}
  with_items:
    - {filename: tigrc, dest: ~/.tigrc }
    - {filename: nanorc, dest: ~/.nanorc }
    - {filename: vimrc, dest: ~/.vimrc }
    - {filename: htoprc, dest: ~/.config/htop/htoprc }
    - {filename: xprofile, dest: ~/.xprofile}
    - {filename: ansible.cfg, dest: ~/.ansible.cfg}

- name: Setup gitconfig
  template:
    dest: ~/.gitconfig
    src: gitconfig.j2

- name: Setup gitignore
  file:
    dest: ~/.gitignore
    src: "{{ ansible_env.PWD }}/roles/ubuntu/files/gitignore"
    force: yes
    state: link

- name: Setup Insults
  sudo: yes
  copy: src=roles/ubuntu/files/sudoers_insults dest=/etc/sudoers.d/insults mode=0440

- name: Update to latest PIP
  sudo: yes
  pip: name=pip state=latest

- name: Install Default PIP Requirements
  pip:
    requirements: "{{ ansible_env.PWD }}/roles/ubuntu/files/requirements.txt"
    state: latest
    virtualenv: ~/.virtualenvs/default3

- name: Remove useless items
  file: path={{ item }} state=absent
  with_items:
    - "~/Templates"
    - "~/Public"
    - "~/examples.desktop"

- name: Create Dev Directory
  file:
    path: "{{ ansible_env.HOME }}/Development"
    state: directory

- name: Crontab - Clear Downloads every 4 hours
  cron:
    job: "find ~/Downloads -type f -mtime +0 -delete"
    hour: "*/4"
    minute: "0"
    name: "Clear Downloads"

- name: Create bin home Directory
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Global Git Status Script
  file:
    state: link
    force: yes
    src: "{{ ansible_env.PWD }}/roles/ubuntu/files/git_status.sh"
    dest: ~/bin/git_status

- name: Setup Postgres Cheatsheet
  sudo: yes
  file:
    state: link
    dest: "/usr/share/man/man1/psqlcheatsheet.1"
    src: "{{ ansible_env.PWD }}/roles/ubuntu/files/psqlcheatsheet"
    force: yes

- include: gpg.yml

- include: zsh.yml

- include: vim.yml

- include: docker.yml
