- name: Install Aptitude
  sudo: yes
  apt:
    name: aptitude
    state: latest

- name: Add Apt Keys
  sudo: yes
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }}
  with_items: apt_keys

- name: Add Apt Repos
  sudo: yes
  apt_repository: "state=present repo='{{ item }}'"
  with_items: apt_repos

- name: Install APT Packages
  sudo: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: apt_packages

- name: Create htop config folder
  file:
    state: directory
    mode: 0700
    path: ~/.config/htop

- name: Setup Configuration Files
  file: dest={{ item.dest }} force=yes state=link src={{ ansible_env.PWD }}/roles/ubuntu/files/{{ item.filename }}
  with_items:
    - {filename: tigrc, dest: ~/.tigrc }
    - {filename: nanorc, dest: ~/.nanorc }
    - {filename: gitconfig, dest: ~/.gitconfig }
    - {filename: vimrc, dest: ~/.vimrc }
    - {filename: htoprc, dest: ~/.config/htop/htoprc }
    - {filename: xprofile, dest: ~/.xprofile}

- name: Setup Insults
  sudo: yes
  copy: src=roles/ubuntu/files/sudoers_insults dest=/etc/sudoers.d/insults mode=0440

# Dont install this on default so that it can be used anywhere
- name: Install MyCLI
  pip: name=mycli state=latest
  sudo: yes

- name: Install Flake8 Linter
  pip: name=flake8 state=latest
  sudo: yes

- name: Update to latest PIP
  sudo: yes
  pip: name=pip state=latest

- name: Install Default PIP Requirements
  pip:
    requirements: "{{ ansible_env.PWD }}/roles/ubuntu/files/requirements.txt"
    virtualenv: ~/.virtualenvs/default

- name: Remove useless items
  file: path={{ item }} state=absent
  with_items:
    - "~/Templates"
    - "~/Public"
    - "~/examples.desktop"

- include: gpg.yml

- include: zsh.yml

- include: vim.yml

- include: development.yml
