- name: Install Aptitude
  sudo: yes
  apt:
    name: aptitude
    state: latest

- name: Add Apt Keys
  sudo: yes
  apt_key: keyserver={{ item.keyserver }} id={{ item.id }}
  with_items: apt_keys

- name: Add Apt Repos
  sudo: yes
  apt_repository: "state=present repo='{{ item }}'"
  with_items: apt_repos

- name: Install APT Packages
  sudo: yes
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: apt_packages

- name: Install PIP Packages
  sudo: yes
  pip: name={{ item }} state=latest
  with_items: pip_packages

- name: Setup Conifguration Files
  file: dest={{ item.dest }} state=link src={{ ansible_env.PWD }}/roles/ubuntu/files/{{ item.filename }}
  with_items:
    - {filename: tigrc, dest: ~/.tigrc }
    - {filename: nanorc, dest: ~/.nanorc }
    - {filename: gitconfig, dest: ~/.gitconfig }
    - {filename: vimrc, dest: ~/.vimrc }
    - {filename: htoprc, dest: ~/.config/htop/htoprc }

- name: Setup Insults
  sudo: yes
  copy: src=roles/ubuntu/files/sudoers_insults dest=/etc/sudoers.d/insults mode=0440

- name: Disable Gnome Keyring for GPG
  sudo: yes
  file: state=absent path={{ item }}
  with_items:
     - /etc/xdg/autostart/gnome-keyring-gpg.desktop
     - /usr/share/upstart/sessions/gnome-keyring-gpg.conf

- name: Remove useless items
  file: path={{ item }} state=absent
  with_items:
    - "~/Templates"
    - "~/Public"
    - "~/examples.desktop"

- include: zsh.yml

- include: vim.yml

- include: development.yml
