- name: mkidr vim
  file:
    path: ~/.vim/autoload
    state: directory
    recurse: yes

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: vimrc repo
  git:
    repo: https://github.com/MichaelAquilina/vimrc.git
    update: yes
    dest: ~/Development/vimrc

- name: link vimrc
  file:
    state: link
    force: yes
    src: ~/Development/vimrc/vimrc
    dest: ~/.vimrc
