# Setup and install atom editor from source
# Based off: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md
- name: Install Atom Dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

- name: Ensure Atom Target Path Exists
  file:
    state: directory
    path: ~/Development/node

- name: Download Atom Git Repo
  git:
    repo: git@github.com:atom/atom
    dest: ~/Development/node/atom
    version: v1.0.0
  notify:
    - build atom
    - bootstrap atom
    - install atom

- name: Setup Atom
  file:
    state: link
    force: true
    src: "{{ ansible_env.PWD }}/roles/unity/files/config.cson"
    dest: ~/.atom/config.cson
