- name: Create themes directory
  sudo: yes
  file:
    state: directory
    path: /usr/share/themes

- name: Download flatabulous
  sudo: yes
  get_url:
    url: https://github.com/anmoljagetia/Flatabulous/archive/master.zip
    dest: /usr/share/themes/Flatabulous.zip

- name: Extract Flatabulous
  sudo: yes
  unarchive:
    dest: /usr/share/themes
    src: /usr/share/themes/Flatabulous.zip
    creates: /usr/share/themes/Flatabulous-master

- name: Set GTK Theme
  gsettings: "schema=org.gnome.desktop.interface key=gtk-theme value=\\'Flatabulous-master\\'"
