- name: Enable pinentry-gtk2
  copy: dest=~/.gnupg/gpg-agent.conf src={{ ansible_env.PWD }}/roles/unity/files/gpg-agent.conf

- include: wallpaper.yml

- include: flatabulous.yml

- include: synapse.yml

- include: unity.yml
