---
ui_apt_repos:
  - 'deb http://archive.canonical.com/ {{ ansible_distribution_release }} partner'
  - 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
  - 'deb http://linux.dropbox.com/ubuntu trusty main'
  - 'deb http://ppa.launchpad.net/meebey/ppa/ubuntu trusty main'
  - 'deb http://ppa.launchpad.net/synapse-core/ppa/ubuntu vivid main'
  - 'deb http://repo.steampowered.com/steam/ precise steam'
  - 'deb http://repository.spotify.com testing non-free'
  - 'deb http://dl.google.com/linux/chrome/deb/ stable main'
  - 'ppa:bitcoin/bitcoin'
  - 'deb http://ppa.launchpad.net/caffeine-developers/ppa/ubuntu vivid main '
  - 'ppa:numix/ppa'
  - 'ppa:webupd8team/atom'
  - 'ppa:rael-gc/scudcloud'

ui_apt_keys:
  - {keyserver: keyserver.ubuntu.com, id: FE1538238AE2A998398D61CA5C39B6F9FC6D77D5}  # smuxi-release
  - {keyserver: keyserver.ubuntu.com, id: BBEBDCB318AD50EC6865090613B00F1FD2C19886}  # Spotify
  - {keyserver: keyserver.ubuntu.com, id: BA1816EF8E75005FCF5E27A1F24AEA9FB05498B7}  # Valve
  - {keyserver: keyserver.ubuntu.com, id: 3DD99294193A09EF9270EEAFE4010F076C2225A4}  # Synapse Core Team
  - {keyserver: keyserver.ubuntu.com, id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E}  # Dropbox
  - {keyserver: keyserver.ubuntu.com, id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991}  # Google
  - {keyserver: keyserver.ubuntu.com, id: DC2887936B4153CA9AFB151B0F678A01569113AE}  # Caffeine Developers

ui_apt_packages:
  - atom
  - bitcoin-qt
  - caffeine
  - compizconfig-settings-manager
  - dconf-tools
  - dropbox
  - gdebi
  - gimp
  - gnome-dictionary
  - hunspell-en-us
  - indicator-multiload
  - kdiff3
  - network-manager-openvpn
  - numix-gtk-theme
  - numix-icon-theme
  - pinentry-gtk2
  - scudcloud
  - skype
  - smuxi
  - spotify-client
  - synapse
  - synaptic
  - terminator
  - tomboy
  - unity-tweak-tool
  - virtualbox-5.0
  - vlc
